POST http://localhost:3001/api/teams
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlkIjoiNjIyZjQ3ZTJmZGFhYTU2OGM3NTE2YTM3IiwiaWF0IjoxNjUxNjkwMjI2LCJleHAiOjE2NTE2OTM4MjZ9.yG_QBkpmP1wGx3CF_Uv5S_laoQikZ_Qm1Jm2ScUj0SE

{
  "gameVersionPokedex": "pokedex-firered.json",
  "team": [
    { "pokemonID": 6 },
    { "pokemonID": 53 },
    { "pokemonID": 24 },
    { "pokemonID": 87 },
    { "pokemonID": 98 },
    { "pokemonID": 134 }
  ],
  "title": "Greatest team ever",
  "description": "Great for early, mid and late game!"
}