GET http://localhost:3001/api/teams/627945f238ecb530334d2b3f

### Response
#### Status Code: 200 OK
#### Headers
- Content-Type: application/json; charset=utf-8
#### Body
```json
{
  "gameVersionPokedex": "firered-pokedex.json",
  "gameVersionName": "FireRed",
  "date": "2022-05-09T16:48:50.258Z",
  "team": [
    {
      "pokemonID": 24,
      "_id": "627945f238ecb530334d2b40"
    },
    {
      "pokemonID": 45,
      "_id": "627945f238ecb530334d2b41"
    },
    {
      "pokemonID": 55,
      "_id": "627945f238ecb530334d2b42"
    },
    {
      "pokemonID": 59,
      "_id": "627945f238ecb530334d2b43"
    },
    {
      "pokemonID": 91,
      "_id": "627945f238ecb530334d2b44"
    },
    {
      "pokemonID": 123,
      "_id": "627945f238ecb530334d2b45"
    }
  ],
  "user": "622f47e2fdaaa568c7516a37",
  "title": "FireRed exclusive team",
  "description": "only missing Electrabuzz",
  "id": "627945f238ecb530334d2b3f"
}
```