PUT http://localhost:3001/api/teams/627969b938ecb530334d2b7e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlkIjoiNjIyZjQ3ZTJmZGFhYTU2OGM3NTE2YTM3IiwiaWF0IjoxNjc0MTU5MTkxLCJleHAiOjE2NzQxNjI3OTF9.UfJYsOBBpxEZqSJcN6nuFWbUZqyb7zXXeYJfMNwyXLg

{
  "team": [
    { "pokemonID": 6 }
  ],
  "title": "new title",
  "description": "new desc"
}

### Response
#### Status Code: 200 OK
#### Headers
- Content-Type: application/json; charset=utf-8
#### Body
```json
{
  "gameVersionPokedex": "firered-pokedex.json",
  "gameVersionName": "FireRed",
  "date": "2022-05-09T19:21:29.206Z",
  "team": [
    {
      "pokemonID": 6,
      "_id": "63c9aa39b4533ea108974e6c"
    }
  ],
  "user": "622f47e2fdaaa568c7516a37",
  "title": "new title",
  "description": "new desc",
  "id": "627969b938ecb530334d2b7e"
}
```