PUT http://localhost:3001/api/teams/61fe992fdf6cd1505f342d77
Content-Type: application/json

{
  "team": [
    {
      "pokemonID": 3,
      "_id": "61fe992fdf6cd1505f342d78"
    },
    {
      "pokemonID": 53,
      "_id": "61fe992fdf6cd1505f342d79"
    },
    {
      "pokemonID": 24,
      "_id": "61fe992fdf6cd1505f342d7a"
    },
    {
      "pokemonID": 87,
      "_id": "61fe992fdf6cd1505f342d7b"
    },
    {
      "pokemonID": 98,
      "_id": "61fe992fdf6cd1505f342d7c"
    },
    {
      "pokemonID": 134,
      "_id": "61fe992fdf6cd1505f342d7d"
    }
  ]
}